Fix for docker build failure
Bumped `python3-dev=3.7.3-r0` => `python3-dev=3.7.4-r0` to fix error in
CircleCI (probably caused by old version being removed):

```
ERROR: unsatisfiable constraints:
  python3-dev-3.7.4-r0:
    breaks: world[python3-dev=3.7.3-r0]
```