Dockerfile: unpin `ca-certificates` to avoid problems
Alpine released a new version of this package which caused a
docker build problem because of the fact this package was pinned in
our `Dockerfile`:

```
ERROR: unsatisfiable constraints:
  ca-certificates-20191127-r0:
    breaks: world[ca-certificates=20190108-r0]
```

There shouldn't be any specific reason to not use the latest version
of `ca-certificates` anyway.