Doc: Note that we should use Helm v2
A new joiner was getting the following error while running the tests using Helm 3.x:

```
FAILED tests/api/models/test_tool.py::test_tool_app_version[chart-with-appVersion] - controlpanel.api.helm.HelmError: Error while opening/parsing helm repository cache: 'reposi...
```

So this is to add a note/warning that you should use Helm 2.x when setting your local environment.